server:
  port: 8080

spring:
  application:
    name: wallpaper
  datasource:
    url: jdbc:mysql://localhost:3306/wallpaper_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 告诉 MyBatis 去哪里找 XML
  type-aliases-package: com.elves.wallpaper.model # 这样 XML 里 type 就可以只写 Wallpaper
  configuration:
    map-underscore-to-camel-case: true